using FastReport;

namespace ProjetoExemplo
{
    public class Program
    {
        public static void Main(string[] args)
        {
            string caminhoRelatorio = Path.Combine(Directory.GetCurrentDirectory(), @"Relatorios\PrimeiroRelatorio.frx");
            Report report = Report.FromFile(caminhoRelatorio);

            List<Pessoa> dados = new List<Pessoa>();
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });
            dados.Add(new Pessoa() { Id = 1, Nome = "Gilseone Moraes", Cidade = "Santa Maria", Celular = "(55) 9 9999-9999" });
            dados.Add(new Pessoa() { Id = 2, Nome = "Paula Severo", Cidade = "Porto Alegre", Celular = "(51) 9 8888-8888" });
            dados.Add(new Pessoa() { Id = 3, Nome = "Maria Silva", Cidade = "Alegrete", Celular = "(51) 9 7777-7777" });
            dados.Add(new Pessoa() { Id = 4, Nome = "José Ricardo Soares", Cidade = "Lagoão", Celular = "(51) 9 6666-6666" });

            report.Report.RegisterData(dados, "PessoaRef");
            report.Prepare();

            using var pdfExport = new FastReport.Export.PdfSimple.PDFSimpleExport();
            using var reportStream = new MemoryStream();
            pdfExport.Export(report, reportStream);
            File.WriteAllBytes("MeuRelatorio.pdf", reportStream.ToArray());
        }
    }
}